from constant import ClientNumber


INSTANCE_NAME= 'R101'
CLIENTS_NUMBER = ClientNumber.TwentyFive.value
FULL_INSTANCE_NAME = f'instances/{INSTANCE_NAME}.{CLIENTS_NUMBER}.txt'
AG_NB_ITERATIONS = 5000
AG_POPULATION_SIZE = 300

AG_WAIT_COEFF = 0.5
AG_DELAY_COEFF = 1.6
AG_NB_VEHICULES_COEFF = 50

AG_CX_PROBA = 0.85
AG_MUT_PROBA = 0.5

# Constantes pour la méthode tabou

TABOU_LIST_SIZE_MAX = 10
TABOU_NEIGHBOURHOOD_SIZE = 200
TABOU_NB_ITERATIONS = 3000