print("Initial Commit")
print("second Commit")
print("third Commit")
print("fourth Commit")
print("fuck")
print("fuck!")
print("fuck2!")
print("fuck321")
print("fuck3!")
print("fuck8798")
print('FranklinFuck2002')
print('Wooowww')
